### ISSUE TITLE
Schematics missing

### ISSUE THREAD

**Issue by muggins** [modmaker/J5-BOB#1]
When you click on the schematics link you get a 404 error.

**Comment by modmaker** [comment]
Right, the link in the wiki page seems to be broken. I'll need to fix that.
In the meantime you can find the schematics in the repository (look in the doc subdirectory) or use the following link: https://github.com/modmaker/J5-BOB/tree/master/doc.

**Comment by muggins** [comment]
The pdfs won’t open on the site either but I was able to download them and then open them.

**Comment by modmaker** [comment]
Fixed the link. The pdfs not opening is probably a browser issue. Firefox doesn't, but Chrome does offer a preview. If this does not work, just click on the 'raw' button to open it.
